import os
from fpdf import FPDF
from datetime import datetime

class CareerReport(FPDF):
    def header(self):
        # Logo
        self.set_fill_color(30, 41, 59)  # Slate 800
        self.rect(0, 0, 210, 40, 'F')
        
        self.set_font('Helvetica', 'B', 24)
        self.set_text_color(255, 255, 255)
        self.cell(0, 20, 'CareerVerse', ln=True, align='C')
        
        self.set_font('Helvetica', 'I', 10)
        self.cell(0, 5, 'AI-Powered Career Counselling Report', ln=True, align='C')
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by CareerVerse AI on {datetime.now().strftime("%Y-%m-%d")}', align='C')

def generate_pdf_report(user_name, performance_level, marks, ml_profile, career_recommendations, output_path):
    pdf = CareerReport()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    # ── Section 1: User Profile ──
    pdf.set_font('Helvetica', 'B', 16)
    pdf.set_text_color(30, 41, 59)
    pdf.cell(0, 10, f"Career Assessment for {user_name}", ln=True)
    pdf.set_font('Helvetica', '', 12)
    pdf.cell(0, 7, f"Performance Level: {performance_level}", ln=True)
    pdf.ln(5)
    
    # ── Section 2: Academic Statistics ──
    pdf.set_font('Helvetica', 'B', 14)
    pdf.cell(0, 10, "Academic Performance Summary", ln=True)
    pdf.set_font('Helvetica', '', 11)
    
    # Create Table Header
    pdf.set_fill_color(241, 245, 249)
    pdf.cell(95, 8, "Subject", 1, 0, 'C', True)
    pdf.cell(95, 8, "Score", 1, 1, 'C', True)
    
    for sub, mark in marks.items():
        pdf.cell(95, 8, f" {sub}", 1)
        pdf.cell(95, 8, f" {mark}", 1, 1, 'C')
    pdf.ln(5)
    
    # ── Section 3: ML Intelligence Profile ──
    pdf.set_font('Helvetica', 'B', 14)
    pdf.set_text_color(37, 99, 235) # Blue 600
    pdf.cell(0, 10, "AI Diagnostic Insight (Strength & Weakness Analysis)", ln=True)
    pdf.set_text_color(30, 41, 59)
    
    pdf.set_font('Helvetica', 'B', 11)
    pdf.cell(40, 7, "Key Strengths:")
    pdf.set_font('Helvetica', '', 11)
    pdf.multi_cell(0, 7, ", ".join(ml_profile.get('strengths', ['Analyzing...'])))
    
    pdf.set_font('Helvetica', 'B', 11)
    pdf.cell(40, 7, "Identified Traits:")
    pdf.set_font('Helvetica', '', 11)
    pdf.multi_cell(0, 7, ", ".join(ml_profile.get('traits', ['Versatile Citizen'])))
    
    if ml_profile.get('weaknesses'):
        pdf.set_font('Helvetica', 'B', 11)
        pdf.cell(40, 7, "Development Areas:")
        pdf.set_font('Helvetica', '', 11)
        pdf.multi_cell(0, 7, ", ".join(ml_profile.get('weaknesses', [])))
    pdf.ln(5)
    
    # ── Section 4: Recommended Career Paths ──
    pdf.set_font('Helvetica', 'B', 14)
    pdf.set_text_color(22, 163, 74) # Green 600
    pdf.cell(0, 10, "Top Recommended Career Paths", ln=True)
    pdf.set_text_color(30, 41, 59)
    
    for path in career_recommendations:
        pdf.set_font('Helvetica', 'B', 12)
        pdf.cell(0, 8, f"• {path.get('path', 'General Study')}", ln=True)
        pdf.set_font('Helvetica', '', 10)
        pdf.multi_cell(0, 6, f"Description: {path.get('description', '')}")
        pdf.set_font('Helvetica', 'I', 10)
        pdf.multi_cell(0, 6, f"Future Scope: {path.get('future_scope', '')}")
        pdf.ln(3)
        
    # ── Section 5: Closing ──
    pdf.ln(10)
    pdf.set_font('Helvetica', 'I', 10)
    pdf.set_text_color(100, 116, 139)
    pdf.multi_cell(0, 5, "Disclaimer: This report is generated by AI based on your academic data. We recommend consulting with professional human counsellors for finalizing significant life decisions.")
    
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    pdf.output(output_path)
    return output_path
